### ISSUE TITLE
use more unique s3 bucket names

### ISSUE THREAD

**Issue by bparees** [openshift/cluster-image-registry-operator#111]
Currently we're using a generated uuid for the bucket name:
https://github.com/openshift/cluster-image-registry-operator/blob/d7c2a4d1559fbff6a0b594e23e6bde16df497530/pkg/storage/s3/s3.go#L161

@cuppett mentioned that this isn't generally considered good enough on S3 because of the universal nature of the bucket namespace.  He had some suggestions for additional values we should include in the name to ensure uniquness.

@cuppett can you please supply the details of the recommendation you were making to me last night?

Thanks.

**Comment by coreydaley** [comment]
@cuppett This should be a quick change if you can get me the specs.

**Comment by cuppett** [comment]
UUID would absolutely be the most unique way to tackle this. However, it provides a while lot of uniqueness and not a lot of insight when scanning an account's bucket list or seeing it referenced in an audit trail. A more common approach is to incorporate a common name, the account number, region and a pinch of randomness.

So instead of a bucket name like:

3eee4f9b-589c-4c88-9967-6cbd7c2691f7

We could auto-generate the name to be:

openshift-registry-321966283653-us-east-1-6ufk3

Where the last 5 characters are selected from an ASCII wheel based on seeding from /dev/urandom or similar.

**Comment by coreydaley** [comment]
@cuppett The bucket name already starts with "image-registry-"
I will add your other suggestions

**Comment by coreydaley** [comment]
It seems that the bucket name can only be 63 characters long.
