### ISSUE TITLE
Publish information about the registry

### ISSUE THREAD

**Issue by dmage** [openshift/cluster-image-registry-operator#29]
In order to make the internal registry discoverable by other components (the API server, for example), we should create the ConfigMap openshift-image-registry/(image-registry-)?public-info with:

  1. our internal host name (image-registry.openshift-image-registry.svc.cluster.local:5000),
  2. our external host name.

This ConfigMap should be readable by `system:authenticated`.

**Comment by bparees** [comment]
In addition to doing this, i'd like to change the api server behavior to default to `image-registry.openshift-image-registry.svc.cluster.local:5000` so that when the apiserver comes up before the registry is installed, it still has the correct value.

The reason this is important is because the imagechangecontroller caches the values of the imagestreams it lists, and the imagestream list/get api uses a decorator to apply the status.dockerImageRepository value based on the internalHostname.

The overall impact of which is that if the imagechangecontroller is up before the registry configuration is available, it will cache values that have an empty status.dockerImageRepository and even after the registry comes up, it will use the incorrect value.

Also of course once we start publishing this information, we need the api server to consume it.

**Comment by bparees** [comment]
Yes, some of this will be part of my work this sprint:  the image-registry operator will need to publish the internalRegistryHostname value into the cluster configuration so it can be consumed by the apisever and controllers (previously those components got the value from master-config.yaml).

and I have a PR for defaulting the value in some of the components themselves here, but i'm not sure it's going to go anywhere: https://github.com/openshift/origin/pull/21160

**Comment by bparees** [comment]
we're now publishing this information (internalhostname anyway) to the image clusterconfig object.

the default hostname should be published there as well, when it is defined.

**Comment by dmage** [comment]
We publish information about all known hostnames to the image.config object.
