### ISSUE TITLE
need to retry failed deploymentconfig rollouts or switch to deployments

### ISSUE THREAD

**Issue by deads2k** [openshift/cluster-image-registry-operator#34]
Upstream deployments constantly try to rollout the latest state until explicitly asked not to.  DeploymentConfigs give up unless triggered again.  Given an operator managed deploymentconfig that should be actively reconciled, you should be retrying failed deployments since they can later succeed.

The current state in openshift/installer is a good example where a blip in the first rollout will cause the image registry to be stuck indefinitely.  Switching to a deployment will resolve this problem.  Alternatively you can rebuild the oc rollout logic.

**Comment by bparees** [comment]
/assign @legionus 

if you want to switch the registry to a deployment for "new" registries you can, but it means you still need to deal with deploymentconfigs for 3.11 registries.  And we are still not prepared to take on migrating those 3.11 registries from a DC to a Deployment since ensuring we can do so without causing an outage, breaking storage, or otherwise blowing things up, isn't something i think we are in a position to tackle.
