### ISSUE TITLE
AdditionalTrustedBundle not being added to the operator pod

### ISSUE THREAD

**Issue by gfvirga** [openshift/cluster-image-registry-operator#397]
Hello,

I just installed a 4.1 cluster, but the registry won't build because it can't trust our internal S3 bucket. I setup the "additionalTrustBundle" during the install, but it didn't seem to do anything during the openshift 4.1

$ `oc logs cluster-image-registry-operator-7f8bbdbddc-nmf5d`
E1003 13:51:16.385613       1 controller.go:255] unable to sync: unable to sync storage configuration: RequestError: send request failed
caused by: Head https://s3bucket.internally.com:9021/ose-dev01_b: x509: certificate signed by unknown authority, requeuing

This feature worked in 4.2. 
I couldn't find the in manuals how to modify the whole cluster additionalbundleCA in openshift4. Could you please help?

**Comment by bparees** [comment]
@ricardomaraschini @dmage were there some bugs around how additionalTrustBundle worked in 4.1?

**Comment by dmage** [comment]
@bparees in 4.2 we added trusted-ca bundles.

@gfvirga did you set `spec.additionalTrustedCA` on the image.config.openshift.io resource?

**Comment by gfvirga** [comment]
Yes I did and it added to the certificate to the openshift-registry pods, but not the operator pods.
The log I am getting is from "cluster-image-registry-operator"

I opened a ticket with the RedHat support and they said the same thing about trusted-ca bundles being added on 4.2. 
We are going to wait until 4.2 is release. 

Thank you for checking this out.

**Comment by bparees** [comment]
> @bparees in 4.2 we added trusted-ca bundles.

@dmage added them to the operator pod?

**Comment by bparees** [comment]
(this seems like a potentially unsupported scenario anyway since it sounds like they are trying to use an s3-equivalent api for storage, not actual s3, which isn't something we explicitly support or can vouch for, but certainly we shouldn't make it impossible to due to CA limitations)

**Comment by gfvirga** [comment]
I just doubled checked and the authentication-operator pod did not get the additional trusted bundle, but S3 bucket connector works fine for me.

@bparees, what is the recommended for Registry storage? We currently have Trident Netapp, S3 and vsphere. S3 is our goto choice and I noticed that vsphere storage would not work.

**Comment by bparees** [comment]
> I just doubled checked and the authentication-operator pod did not get the additional trusted bundle, but S3 bucket connector works fine for me.

what won't work is having the operator create buckets for you.   if you created your own buckets and just pointed the registry to them, then yeah it makes sense that that would work once you got the right CAs in the registry pod, even if the operator pod doesn't have them.

> @bparees, what is the recommended for Registry storage? We currently have Trident Netapp, S3 and vsphere. S3 is our goto choice and I noticed that vsphere storage would not work.

The only s3 api solution we test with is AWS S3.  We are looking into NooBaa/MCS in the future.

For non-cloud-based options, we don't get super opinionated, we just require that you provide a PV that can be mounted read/write/many (since we have to mount it to multiple nodes) for which many people use NFS, Gluster, and Ceph.  With OCS being Ceph based moving forward, that is likely the best future direction.
