### ISSUE TITLE
Migrate from operator-sdk

### ISSUE THREAD

**Issue by legionus** [openshift/cluster-image-registry-operator#40]
Since the operator has deleted the entire API [1], we are on the unsupported version in the vendor that cannot be updated. Of course, you can live with it for now, but eventually we need to rewrite everything using some another API.

[1] https://github.com/operator-framework/operator-sdk/commit/a78c1024ee091c666f7a29a4ab2fb8ffd9e1083b

**Comment by legionus** [comment]
See also github.com/operator-framework/operator-sdk/issues/633

**Comment by gabemontero** [comment]
I'm also thinking that https://github.com/operator-framework/operator-sdk/issues/382 is some sort of umbrella or is at least related to this SDK evolution that is potentially making them untenable to us.

That issue was what prompted some of my questions in scrum over the last few weeks about "how will the SDK enable migration for us" ... which as @legionus has discovered ....their answer seems to be "they will not"

**Comment by gabemontero** [comment]
ah check that ... just saw https://github.com/operator-framework/operator-sdk/issues/633#issuecomment-430716209

still .... seems like a wait and see approach could be warranted, at least until we see what they produce

**Comment by legionus** [comment]
Since `operator-sdk` suggests using the `controller-runtime`, I no longer see the point in the `operator-sdk` itself.

**Comment by legionus** [comment]
We have https://github.com/kubernetes/sample-controller as an example.

**Comment by legionus** [comment]
Done
